"""Short Azerbaijani notes describing what each English resource gives you.

Every video and reading in the plan gets a `note` field. Notes describe the
*type and style* of the source (what you get and how to use it) — they never
invent claims about a specific video's content, so they stay accurate even if a
channel renames or re-uploads a video.
"""

# (channel substring, Azerbaijani note) — first match wins.
CHANNEL_RULES = [
    ("statquest", "Sadə dildə, addım-addım izah — statistik/ML anlayışlarını intuisiya səviyyəsində anlamaq üçün."),
    ("josh starmer", "Sadə dildə, addım-addım izah — anlayışı intuisiya səviyyəsində anlamaq üçün."),
    ("krish naik", "Praktik ML/data dərsləri: kod yazır və nəticəni ekranda göstərir."),
    ("corey schafer", "Python-un əsaslarını addım-addım, çox təmiz şəkildə izah edən klassik dərslər."),
    ("freecodecamp", "Sıfırdan başlayanlar üçün uzun, praktik kurs — özün də eyni vaxtda kod yaz."),
    ("karpathy", "Kodu sıfırdan yazaraq ən dərin izah. Yavaş izlə, hər sətri özün təkrar yaz."),
    ("andrew ng", "Nəzəriyyə və praktika balanslı ML/DL dərsləri; konsepti düzgün qurmaq üçün."),
    ("deeplearning.ai", "Nəzəriyyə və praktika balanslı ML/DL dərsləri; konsepti düzgün qurmaq üçün."),
    ("yannic kilcher", "Elmi məqalələri sətir-sətir izah edir — paper oxumağı öyrənmək üçün əla."),
    ("arjancodes", "Kod dizaynı və təmiz Python arxitekturası; peşəkar kod vərdişləri üçün."),
    ("3blue1brown", "Vizual, intuitiv izah. Əvvəlcə bunu izlə, sonra hesablamanı əl ilə özün apar."),
    ("ken jee", "Data/AI karyerası, portfolio və müsahibə məsləhətləri."),
    ("techworld with nana", "DevOps/CI-CD/Docker/Kubernetes mövzularını praktik və çox aydın izah edir."),
    ("hugging face", "Kitabxananın öz dərsləri: transformers/datasets ilə real kod nümunələri."),
    ("keith galli", "NumPy/Pandas əməliyyatlarını canlı kodla, addım-addım göstərir."),
    ("assemblyai", "API və LLM tətbiqləri üzrə praktik, addım-addım dərslər."),
    ("sentdex", "Python/CV/data üzrə layihə əsaslı dərslər."),
    ("fireship", "Qısa, sürətli icmallar — anlayışı tez tutmaq, sonra dərinləşmək üçün."),
    ("khan academy", "Riyaziyyat əsaslarını sıfırdan izah edən qısa dərslər."),
    ("alex the analyst", "SQL və analitik düşüncə üzrə praktik dərslər."),
    ("made with ml", "ML layihəsini production-a çıxarmaq üzrə sistemli kurs materialı."),
    ("aladdin persson", "PyTorch-da modelləri sıfırdan yazmaq üzrə praktik dərslər."),
    ("mcoding", "Python-un dərinlikləri, test və performans üzrə aydın izahlar."),
    ("renotte", "CV/YOLO/OCR kimi real layihələri başdan-sona qurur."),
    ("abhishek thakur", "Kaggle və ML layihə axını üzrə praktik təcrübə."),
    ("cs224n", "Universitet səviyyəsində NLP mühazirələri — dərin nəzəri əsas."),
    ("strang", "Klassik xətti cəbr mühazirələri: nəzəri əsas və intuisiya."),
    ("trelis", "LoRA/fine-tuning və LLM xərc optimallaşdırması üzrə praktik videolar."),
    ("data school", "Pandas/scikit-learn əməliyyatlarını qısa və aydın şəkildə göstərir."),
    ("daniel bourke", "PyTorch ilə tam ML iş axını və layihə əsaslı dərslər."),
    ("llamaindex", "RAG, chunking və advanced retrieval üzrə rəsmi dərslər."),
    ("langchain", "Agent və RAG framework-ləri ilə praktik nümunələr."),
    ("roboflow", "CV dataset, annotasiya və YOLO üzrə praktik dərslər."),
    ("ultralytics", "YOLO modellərinin təlimi və metrikaları üzrə rəsmi material."),
    ("distrotube", "Linux terminal və alətləri üzrə praktik ekran dərsləri."),
    ("mutual information", "ML konseptlərini nəzəri cəhətdən dərindən izah edir."),
    ("pytorch", "PyTorch-un rəsmi video/sənəd materialı — dəqiq API davranışı."),
    ("python engineer", "PyTorch və Python mühəndisliyi üzrə praktik videolar."),
    ("openai", "API, prompt və function calling üzrə rəsmi nümunələr."),
    ("james briggs", "Vektor axtarışı və RAG üzrə praktik nümunələr."),
    ("sam witteveen", "Agent, MCP və LLM tətbiqləri üzrə praktik videolar."),
    ("learnopencv", "CV alqoritmlərini kod və nümunələrlə izah edir."),
    ("exponent", "Müsahibə formatı və sistem dizaynı nümunələri."),
    ("visual studio code", "Rəsmi quraşdırma təlimatı — mühiti düzgün qurmaq üçün."),
    ("learngitbranching", "İnteraktiv Git məşqi — branch/merge-i oynayaraq öyrən."),
    ("github", "Platformanın rəsmi dərsləri və iş axınları."),
    ("missing semester", "Terminal, alət zənciri və mühəndislik vərdişləri üzrə universitet mühazirəsi."),
    ("networkchuck", "Şəbəkə və SSH mövzularını enerjili, praktik şəkildə izah edir."),
    ("web dev simplified", "HTTP/REST kimi anlayışları sadə dildə izah edir."),
    ("steve brunton", "SVD və xətti cəbr üzrə professor səviyyəsində izahlar."),
    ("codebasics", "Python/ML/data üzrə praktik dərslər."),
    ("kaggle", "Platformanın rəsmi mini-kursları — praktik məşqlərlə."),
    ("kimberly fessel", "Seaborn və vizualizasiya üzrə fokuslu dərslər."),
    ("charming data", "Plotly ilə interaktiv vizualizasiya dərsləri."),
    ("mode analytics", "SQL-i analitik tapşırıqlarla öyrədən praktik kurs."),
    ("hussein nasser", "Database və performans mövzularını dərin izah edir."),
    ("pretty printed", "SQLAlchemy və backend alətləri üzrə qısa dərslər."),
    ("optuna", "Hiperparametr optimizasiyası üzrə rəsmi nümunələr."),
    ("christoph molnar", "Model interpretasiyası kitabının müəllifindən izahlar."),
    ("ibm", "Anlayışları 10-15 dəqiqədə texniki dildə izah edir."),
    ("cohere", "Reranking-in axtarış keyfiyyətini necə yaxşılaşdırdığını göstərir."),
    ("matthew berman", "Açıq LLM-ləri lokal işlətmək üzrə praktik videolar."),
    ("vllm", "LLM servisini sürətli qurmaq üzrə rəsmi material."),
    ("simon willison", "LLM praktikası və prompt injection təhlükəsizliyi üzrə çıxışlar."),
    ("anthropic", "Claude API, prompt engineering və MCP üzrə rəsmi sənəd."),
    ("ai engineer", "AI mühəndisliyi karyerası və müasir alətlər üzrə söhbətlər."),
    ("ai jason", "LLM tətbiqlərini başdan-sona qurma üzrə praktik videolar."),
    ("pyimagesearch", "CV üzrə praktik məqalə və dərslər."),
    ("digitalsreeni", "Seqmentasiya və şəkil emalı üzrə addım-addım dərslər."),
    ("microsoft", "ONNX Runtime ilə sürət optimallaşdırması üzrə rəsmi material."),
    ("datatalksclub", "MLOps Zoomcamp: sistemli, layihə əsaslı MLOps kursu."),
    ("evidently", "Drift və model monitorinqi üzrə praktik nümunələr."),
    ("dvc", "Data versiyalama üzrə rəsmi dərs."),
    ("streamlit", "Data tətbiqini tez UI ilə göstərmək üzrə dərslər."),
    ("data professor", "Data tətbiqini tez UI ilə göstərmək üzrə dərslər."),
    ("neetcode", "Alqoritmik müsahibə pattern-ləri üzrə sistemli hazırlıq."),
    ("digital sreeni", "Şəkil emalı və seqmentasiya üzrə praktik dərslər."),
]

VIDEO_FALLBACK = "Praktik video material — mövzunu nümunələrlə göstərir."

# (substring in source/host, Azerbaijani note) — first match wins.
SOURCE_RULES = [
    ("arxiv.org", "Orijinal elmi məqalə (paper): konseptin ilk mənbəyi. Abstrakt və əsas bölmələri oxu."),
    ("docs.python.org", "Rəsmi Python sənədi — dəqiq və tam istinad mənbəyi."),
    ("peps.python.org", "Rəsmi Python təklifi: üslub və dil qaydaları."),
    ("pytorch.org", "Rəsmi PyTorch sənədi — kod nümunələri ilə praktik izah."),
    ("scikit-learn.org", "Rəsmi scikit-learn sənədi: API, parametrlər və nümunələr."),
    ("huggingface.co", "Hugging Face sənədi/kursu: transformer-lərlə real kod nümunələri."),
    ("pandas.pydata.org", "Rəsmi Pandas sənədi (user guide) — funksiyaların dəqiq davranışı."),
    ("numpy.org", "Rəsmi NumPy sənədi: broadcasting, axis və linalg detalları."),
    ("matplotlib.org", "Rəsmi Matplotlib sənədi: qrafik növləri, stillər, alt-fiqiurlar."),
    ("seaborn.pydata.org", "Rəsmi Seaborn sənədi: statistik vizualizasiya növləri."),
    ("plotly.com", "Rəsmi Plotly sənədi: interaktiv qrafiklər."),
    ("docs.scipy.org", "SciPy statistik funksiyalar sənədi — testlər və paylanmalar."),
    ("mlflow.org", "Rəsmi MLflow sənədi: eksperiment izləmə və model registry."),
    ("fastapi.tiangolo.com", "Rəsmi FastAPI sənədi: endpoint, validasiya, deploy."),
    ("docs.docker.com", "Rəsmi Docker sənədi: image, container, compose, best practices."),
    ("kubernetes.io", "Rəsmi Kubernetes sənədi (əsas anlayışlar)."),
    ("postgresql.org", "Rəsmi PostgreSQL sənədi: SQL sintaksisi və dərslik."),
    ("use-the-index-luke.com", "Index və sorğu performansı üzrə praktik bələdçi."),
    ("w3schools.com", "SQL əsaslarını qısa nümunələrlə öyrədən təlimat."),
    ("sqlbolt.com", "İnteraktiv SQL məşqləri — brauzerdə sorğu yazaraq öyrən."),
    ("mode.com", "SQL-i analitik tapşırıqlarla öyrədən praktik kurs."),
    ("github.com/skills", "GitHub Skills: brauzerdə addım-addım praktik məşq."),
    ("github.com/datatalksclub", "MLOps Zoomcamp materialları (repository)."),
    ("github.com/karpathy", "Karpathy-nin istinad implementasiyaları (micrograd, nanoGPT)."),
    ("github.com/ageron", "Kitabın rəsmi kod nümunələri (notebook-lar)."),
    ("github.com/openai", "Rəsmi nümunələr toplusu (cookbook) — kopyala və sına."),
    ("github.com/kaggle", "Rəsmi alətin repository-si: quraşdırma və istifadə."),
    ("github.com/chiphuyen", "ML sistem dizaynı materialları (repository)."),
    ("github.com", "Kod repository-si: README, nümunələr və struktur."),
    ("docs.github.com", "GitHub-ın rəsmi sənədi: addım-addım təlimatlar."),
    ("git-scm.com", "Git-in rəsmi kitabı (Pro Git) — dərin istinad mənbəyi."),
    ("learngitbranching.js.org", "İnteraktiv Git məşqi: branch/merge-i oynayaraq öyrən."),
    ("missing.csail.mit.edu", "MIT 'Missing Semester' kursu: terminal və alət zənciri."),
    ("ubuntu.com", "Komanda sətri əsaslarını göstərən rəsmi təlimat."),
    ("gnu.org", "GNU alətlərinin rəsmi manual-ı (coreutils, bash, awk)."),
    ("makefiletutorial.com", "Makefile-ları nümunələrlə izah edən praktik dərs."),
    ("docs.pytest.org", "Rəsmi pytest sənədi: fixture, parametrize, plugin-lər."),
    ("docs.astral.sh", "ruff: linting və formatlama alətinin sənədi."),
    ("docs.pydantic.dev", "Rəsmi Pydantic sənədi: sxema və validasiya."),
    ("requests.readthedocs.io", "Rəsmi requests sənədi: HTTP sorğuları və xəta idarəsi."),
    ("packaging.python.org", "Rəsmi paketləmə təlimatı: layihəni paylaşıla bilən etmək."),
    ("pip.pypa.io", "Rəsmi pip sənədi: requirements formatı və asılılıqlar."),
    ("12factor.net", "12-Factor App: konfiqurasiya və sirrlərin idarəsi prinsipləri."),
    ("kaggle.com", "Kaggle resursu: praktik məşqlər, dataset-lər, notebook-lar."),
    ("colab.research.google.com", "Google Colab: buludda pulsuz GPU ilə işləmək."),
    ("jupyter.org", "Jupyter ekosistemi: notebook ən yaxşı təcrübələri."),
    ("deeplearningbook.org", "DL nəzəriyyəsi kitabı — riyazi əsas və isbatlar (seçilmiş bölmələr)."),
    ("mml-book.github.io", "Mathematics for ML kitabı — ML üçün riyaziyyatın sistemli izahı."),
    ("statlearning.com", "ISLR kitabı: nəzəriyyə + R kod nümunələri (ML əsasları)."),
    ("d2l.ai", "Dive into Deep Learning — kod ilə birlikdə nəzəriyyə."),
    ("jalammar.github.io", "Vizuallarla yazılmış klassik izahlar (Transformer, word2vec, attention)."),
    ("huyenchip.com", "Chip Huyen: ML sistem dizaynı və müsahibə kitabı."),
    ("madewithml.com", "ML layihəsini production-a çıxarmaq üzrə sistemli kurs."),
    ("fullstackdeeplearning.com", "FSDL kursu: ML məhsulunun tam həyat dövrü."),
    ("ml-ops.org", "MLOps prinsipləri və olgunluq modelləri."),
    ("christophm.github.io", "Interpretable ML kitabı: model izahı metodları."),
    ("lilianweng.github.io", "Agent/LLM mövzularında dərin texniki xülasə."),
    ("simonwillison.net", "LLM praktikası və prompt injection üzrə tanınmış bloq."),
    ("ruder.io", "Optimizasiya alqoritmlərinin müqayisəli klassik yazısı."),
    ("distill.pub", "Vizual və dərin texniki izahlar (Distill jurnalı)."),
    ("seeing-theory.brown.edu", "İnteraktiv vizualizasiya ilə ehtimal öyrənmək."),
    ("setosa.io", "İnteraktiv izah: şərti ehtimal və Bayes."),
    ("cs231n.stanford.edu", "Stanford CS231n kurs materialı (kompüter görmə)."),
    ("web.stanford.edu", "Stanford kurs materialı (NLP/CS224n)."),
    ("stanford.edu", "Stanford kurs materialı — universitet səviyyəsində izah."),
    ("developers.google.com", "Google-ın rəsmi ML təlimatı (Crash Course)."),
    ("ai.google.dev", "MediaPipe və on-device ML üzrə rəsmi sənəd."),
    ("platform.openai.com", "API provayderinin rəsmi sənədi: prompt və parametrlər."),
    ("docs.anthropic.com", "API provayderinin rəsmi sənədi: prompt və alətlər."),
    ("promptingguide.ai", "Prompt engineering bələdçisi — texnikalar və nümunələr toplusu."),
    ("python.langchain.com", "Rəsmi LangChain sənədi: agent, tool, memory."),
    ("docs.llamaindex.ai", "Rəsmi LlamaIndex sənədi: RAG pipeline-ları."),
    ("docs.trychroma.com", "Rəsmi Chroma sənədi: vektor bazası və metadata filtri."),
    ("qdrant.tech", "Rəsmi Qdrant sənədi: vektor indeksləri və axtarış."),
    ("docs.ragas.io", "RAGAS: RAG-ın avtomatik qiymətləndirilməsi."),
    ("docs.vllm.ai", "vLLM: yüksək sürətli LLM servisi."),
    ("docs.smith.langchain.com", "LangSmith: agent trace-ləri və monitorinq."),
    ("docs.wandb.ai", "Weights & Biases: eksperiment izləmə və panolar."),
    ("docs.evidentlyai.com", "Evidently: drift hesabatı və monitorinq."),
    ("docs.streamlit.io", "Streamlit: data tətbiqi üçün sadə UI."),
    ("gradio.app", "Gradio: model demosu üçün UI (HF Spaces ilə işləyir)."),
    ("docs.opencv.org", "Rəsmi OpenCV Python dərsləri — kod nümunələri ilə."),
    ("docs.ultralytics.com", "Rəsmi Ultralytics/YOLO sənədi: təlim, metrikalar, tracking."),
    ("roboflow.com", "Annotasiya və dataset idarəsi platforması."),
    ("onnx.ai", "ONNX: model mübadilə formatı və runtime sənədi."),
    ("xgboost.readthedocs.io", "Rəsmi XGBoost sənədi: parametrlər və early stopping."),
    ("lightgbm.readthedocs.io", "Rəsmi LightGBM sənədi: sürətli boosting parametrləri."),
    ("catboost.ai", "Rəsmi CatBoost sənədi: kateqorik data ilə iş."),
    ("optuna.readthedocs.io", "Rəsmi Optuna sənədi: Bayesian hiperparametr optimizasiyası."),
    ("shap.readthedocs.io", "Rəsmi SHAP sənədi: model izahı qrafikləri."),
    ("umap-learn.readthedocs.io", "Rəsmi UMAP sənədi: ölçü azaltma və vizualizasiya."),
    ("imbalanced-learn.org", "imbalanced-learn: balanssız data üsulları (SMOTE və s.)."),
    ("sbert.net", "Sentence Transformers: mətn embedding-ləri üzrə sənəd."),
    ("dvc.org", "Rəsmi DVC sənədi: data və pipeline versiyalama."),
    ("airflow.apache.org", "Rəsmi Airflow sənədi: DAG-lar və orkestrasiya."),
    ("modelcontextprotocol.io", "MCP sənədi: tool/server primitivləri."),
    ("genai.owasp.org", "OWASP LLM Top 10: LLM tətbiqlərinin əsas təhlükəsizlik riskləri."),
    ("12factor", "12-Factor App prinsipləri."),
    ("realpython.com", "Real Python məqalələri: praktik Python nümunələri."),
    ("towardsdatascience.com", "Praktik blog yazısı — nümunə və izahlarla."),
    ("eugeneyan.com", "Praktik ML/LLM məhsul tövsiyələri (bloq)."),
    ("huyenchip", "Chip Huyen: ML sistem dizaynı və müsahibə materialları."),
    ("wikipedia.org", "Ensiklopedik xülasə — anlayışı tez xatırlamaq üçün."),
    ("mathinsight.org", "Riyazi anlayışların qısa və vizual izahı."),
    ("themuse.com", "STAR metodu ilə davranış suallarına cavab strukturu."),
    ("conventionalcommits.org", "Commit mesajı konvensiyası (komanda standartı)."),
    ("makeareadme.com", "README şablonu və struktur tövsiyələri."),
    ("leetcode.com", "Alqoritmik məşq platforması — müsahibə hazırlığı."),
    ("roadmap.sh", "Vakansiya tələblərinə uyğun bacarıq yol xəritəsi."),
    ("karpathy.ai", "Karpathy-nin kurs materialı və praktik DL tövsiyələri."),
    ("karpathy.github.io", "Karpathy-nin 'neural networks necə öyrədilməlidir' praktik məqaləsi."),
    ("aws.amazon.com", "Bulud provayderinin ML xidmətləri (qiymət və imkanlar)."),
    ("cloud.google.com", "Bulud provayderinin rəsmi ML platforması sənədi."),
    ("pyimagesearch.com", "CV üzrə praktik məqalələr və kod nümunələri."),
    ("colah.github.io", "LSTM/RNN-in klassik vizual izahı."),
    ("jakevdp.github.io", "Python Data Science Handbook: NumPy/Pandas üçün praktik nümunələr."),
    ("wesmckinney.com", "Python for Data Analysis kitabı: Pandas müəllifindən dərslik."),
    ("christophm", "Interpretable ML kitabı — model izahı metodları."),
    ("statlearning", "ISLR kitabı — ML nəzəriyyəsi və kod nümunələri."),
    ("deeplearningbook", "DL nəzəriyyəsi kitabı — riyazi əsas."),
    ("guidetodatamining", "Data mining əsasları."),
]

READING_SEARCH_NOTE = "Axtarış linki — mövzu üzrə əlavə izahlar və məqalələr tapmaq üçün."
READING_FALLBACK = "Rəsmi sənəd/məqalə — mövzunun detallarını dəqiqləşdirmək üçün."


def video_note(channel):
    """Return a short Azerbaijani note for a YouTube channel name."""
    parts = [p.strip().lower() for p in str(channel).replace(",", "/").split("/") if p.strip()]
    for part in parts:
        for needle, note in CHANNEL_RULES:
            if needle in part:
                return note
    for part in parts:
        for needle, note in CHANNEL_RULES:
            if needle in part:
                return note
    return VIDEO_FALLBACK


def reading_note(source, url):
    """Return a short Azerbaijani note for a reading source/URL."""
    hay = ("%s %s" % (source or "", url or "")).lower()
    if "google.com/search" in hay:
        return READING_SEARCH_NOTE
    for needle, note in SOURCE_RULES:
        if needle in hay:
            return note
    return READING_FALLBACK
